name: Build Mod and Deploy Docs

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Set up JDK 1.8
                uses: actions/setup-java@v2
                with:
                    java-version: '8'
                    distribution: 'temurin'
                    cache: 'gradle'

            - name: Validate Gradle wrapper
              uses: gradle/wrapper-validation-action@v1

            - run: ./gradlew build javadoc

            - name: Deploy Docs if push
              uses: JamesIves/github-pages-deploy-action@4.1.5
              if: ${{ github.event_name == 'push' }}
              with:
                  branch: gh-pages
                  folder: build/docs/javadoc
